<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User Entity
 * 
 * Represents a user of the system (Client, Employee, Admin, or Developer).
 * Implements Symfony's security interfaces for authentication and authorization.
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cet email.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /** @var int|null The unique identifier of the user */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /** @var string|null The email address used for login */
    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /** @var int Number of "strikes" (missed reservations). Account is banned after 3 strikes. */
    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $strikes = 0;

    /** @var \DateTimeImmutable|null Expiration date of the user's ban */
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $banExpiresAt = null;

    /** @var string|null The user's first name */
    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    /** @var string|null The user's last name */
    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    /** @var float Total revenue generated by products created by this user */
    #[ORM\Column(type: 'float', options: ['default' => 0])]
    private float $cumulativeRevenue = 0.0;

    /** @var int Total number of items sold from products created by this user */
    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $cumulativeSoldItems = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_CLIENT
        $roles[] = 'ROLE_CLIENT';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getStrikes(): int
    {
        return $this->strikes;
    }

    public function setStrikes(int $strikes): static
    {
        $this->strikes = $strikes;

        return $this;
    }

    public function getBanExpiresAt(): ?\DateTimeImmutable
    {
        return $this->banExpiresAt;
    }

    public function setBanExpiresAt(?\DateTimeImmutable $banExpiresAt): static
    {
        $this->banExpiresAt = $banExpiresAt;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCumulativeRevenue(): float
    {
        return $this->cumulativeRevenue;
    }

    public function setCumulativeRevenue(float $cumulativeRevenue): static
    {
        $this->cumulativeRevenue = $cumulativeRevenue;

        return $this;
    }

    public function addCumulativeRevenue(float $amount): static
    {
        $this->cumulativeRevenue += $amount;

        return $this;
    }

    public function getCumulativeSoldItems(): int
    {
        return $this->cumulativeSoldItems;
    }

    public function setCumulativeSoldItems(int $cumulativeSoldItems): static
    {
        $this->cumulativeSoldItems = $cumulativeSoldItems;

        return $this;
    }

    public function addCumulativeSoldItems(int $count): static
    {
        $this->cumulativeSoldItems += $count;

        return $this;
    }
    /** @var \Doctrine\Common\Collections\Collection<int, Product> Products created by this user (if Employee/Admin) */
    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Product::class)]
    private \Doctrine\Common\Collections\Collection $products;

    public function __construct()
    {
        $this->products = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @return \Doctrine\Common\Collections\Collection<int, Product>
     */
    public function getProducts(): \Doctrine\Common\Collections\Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setCreatedBy($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCreatedBy() === $this) {
                $product->setCreatedBy(null);
            }
        }

        return $this;
    }
}
